/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AcceptInviteRouteImport } from './routes/accept-invite'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as AccountingAccountGroupsRouteImport } from './routes/accounting.account-groups'
import { Route as AccountingBalanceSheetRouteImport } from './routes/accounting.balance-sheet'
import { Route as AccountingBooksRouteImport } from './routes/accounting.books'
import { Route as AccountingCashFlowRouteImport } from './routes/accounting.cash-flow'
import { Route as AccountingChartOfAccountsRouteImport } from './routes/accounting.chart-of-accounts'
import { Route as AccountingCostCentresRouteImport } from './routes/accounting.cost-centres'
import { Route as AccountingFiscalYearsRouteImport } from './routes/accounting.fiscal-years'
import { Route as AccountingJournalEntriesRouteImport } from './routes/accounting.journal-entries'
import { Route as AccountingLedgersRouteImport } from './routes/accounting.ledgers'
import { Route as AccountingProfitLossRouteImport } from './routes/accounting.profit-loss'
import { Route as AccountingReceivablesRouteImport } from './routes/accounting.receivables'
import { Route as AccountingTrialBalanceRouteImport } from './routes/accounting.trial-balance'
import { Route as AccountingVouchersRouteImport } from './routes/accounting.vouchers'
import { Route as AdminApiKeysRouteImport } from './routes/admin.api-keys'
import { Route as AdminAuditLogRouteImport } from './routes/admin.audit-log'
import { Route as AdminBillingRouteImport } from './routes/admin.billing'
import { Route as AdminDepartmentsRouteImport } from './routes/admin.departments'
import { Route as AdminIntegrationsRouteImport } from './routes/admin.integrations'
import { Route as AdminRolesRouteImport } from './routes/admin.roles'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminTeamsRouteImport } from './routes/admin.teams'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as BankingAccountsRouteImport } from './routes/banking.accounts'
import { Route as BankingStatementsRouteImport } from './routes/banking.statements'
import { Route as BankingTransactionsRouteImport } from './routes/banking.transactions'
import { Route as CrmActivitiesRouteImport } from './routes/crm.activities'
import { Route as CrmLeadsRouteImport } from './routes/crm.leads'
import { Route as CrmOpportunitiesRouteImport } from './routes/crm.opportunities'
import { Route as HrmsAttendanceRouteImport } from './routes/hrms.attendance'
import { Route as HrmsEmployeesRouteImport } from './routes/hrms.employees'
import { Route as HrmsLeavesRouteImport } from './routes/hrms.leaves'
import { Route as HrmsPayrollRouteImport } from './routes/hrms.payroll'
import { Route as InventoryCategoriesRouteImport } from './routes/inventory.categories'
import { Route as InventoryLowStockRouteImport } from './routes/inventory.low-stock'
import { Route as InventoryProductsRouteImport } from './routes/inventory.products'
import { Route as InventoryStockMovementsRouteImport } from './routes/inventory.stock-movements'
import { Route as InventoryWarehousesRouteImport } from './routes/inventory.warehouses'
import { Route as OperationsComplianceRouteImport } from './routes/operations.compliance'
import { Route as OperationsWorkflowsRouteImport } from './routes/operations.workflows'
import { Route as PurchasesBillsRouteImport } from './routes/purchases.bills'
import { Route as PurchasesExpensesRouteImport } from './routes/purchases.expenses'
import { Route as PurchasesPurchaseOrdersRouteImport } from './routes/purchases.purchase-orders'
import { Route as PurchasesVendorsRouteImport } from './routes/purchases.vendors'
import { Route as ReportsFinancialRouteImport } from './routes/reports.financial'
import { Route as ReportsGstRouteImport } from './routes/reports.gst'
import { Route as ReportsInventoryRouteImport } from './routes/reports.inventory'
import { Route as ReportsSalesRouteImport } from './routes/reports.sales'
import { Route as SalesCustomersRouteImport } from './routes/sales.customers'
import { Route as SalesInvoicesRouteImport } from './routes/sales.invoices'
import { Route as SalesPaymentsRouteImport } from './routes/sales.payments'
import { Route as SalesQuotationsRouteImport } from './routes/sales.quotations'
import { Route as SalesSalesOrdersRouteImport } from './routes/sales.sales-orders'
import { Route as SecurityMfaRouteImport } from './routes/security.mfa'
import { Route as SecuritySessionsRouteImport } from './routes/security.sessions'
import { Route as SuperAdminAnnouncementsRouteImport } from './routes/super-admin.announcements'
import { Route as SuperAdminApiUsageRouteImport } from './routes/super-admin.api-usage'
import { Route as SuperAdminAuditLogsRouteImport } from './routes/super-admin.audit-logs'
import { Route as SuperAdminCouponsRouteImport } from './routes/super-admin.coupons'
import { Route as SuperAdminDashboardRouteImport } from './routes/super-admin.dashboard'
import { Route as SuperAdminFeaturesRouteImport } from './routes/super-admin.features'
import { Route as SuperAdminInvoicesRouteImport } from './routes/super-admin.invoices'
import { Route as SuperAdminOrganizationsRouteImport } from './routes/super-admin.organizations'
import { Route as SuperAdminPaymentsRouteImport } from './routes/super-admin.payments'
import { Route as SuperAdminPermissionsRouteImport } from './routes/super-admin.permissions'
import { Route as SuperAdminRolesRouteImport } from './routes/super-admin.roles'
import { Route as SuperAdminSettingsRouteImport } from './routes/super-admin.settings'
import { Route as SuperAdminSubscriptionsRouteImport } from './routes/super-admin.subscriptions'
import { Route as SuperAdminSystemHealthRouteImport } from './routes/super-admin.system-health'
import { Route as SuperAdminUsersRouteImport } from './routes/super-admin.users'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInviteRoute = AcceptInviteRouteImport.update({
  id: '/accept-invite',
  path: '/accept-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountingAccountGroupsRoute = AccountingAccountGroupsRouteImport.update({
  id: '/accounting/account-groups',
  path: '/accounting/account-groups',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountingBalanceSheetRoute = AccountingBalanceSheetRouteImport.update({
  id: '/accounting/balance-sheet',
  path: '/accounting/balance-sheet',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountingBooksRoute = AccountingBooksRouteImport.update({
  id: '/accounting/books',
  path: '/accounting/books',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountingCashFlowRoute = AccountingCashFlowRouteImport.update({
  id: '/accounting/cash-flow',
  path: '/accounting/cash-flow',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountingChartOfAccountsRoute =
  AccountingChartOfAccountsRouteImport.update({
    id: '/accounting/chart-of-accounts',
    path: '/accounting/chart-of-accounts',
    getParentRoute: () => rootRouteImport,
  } as any)
const AccountingCostCentresRoute = AccountingCostCentresRouteImport.update({
  id: '/accounting/cost-centres',
  path: '/accounting/cost-centres',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountingFiscalYearsRoute = AccountingFiscalYearsRouteImport.update({
  id: '/accounting/fiscal-years',
  path: '/accounting/fiscal-years',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountingJournalEntriesRoute =
  AccountingJournalEntriesRouteImport.update({
    id: '/accounting/journal-entries',
    path: '/accounting/journal-entries',
    getParentRoute: () => rootRouteImport,
  } as any)
const AccountingLedgersRoute = AccountingLedgersRouteImport.update({
  id: '/accounting/ledgers',
  path: '/accounting/ledgers',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountingProfitLossRoute = AccountingProfitLossRouteImport.update({
  id: '/accounting/profit-loss',
  path: '/accounting/profit-loss',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountingReceivablesRoute = AccountingReceivablesRouteImport.update({
  id: '/accounting/receivables',
  path: '/accounting/receivables',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountingTrialBalanceRoute = AccountingTrialBalanceRouteImport.update({
  id: '/accounting/trial-balance',
  path: '/accounting/trial-balance',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountingVouchersRoute = AccountingVouchersRouteImport.update({
  id: '/accounting/vouchers',
  path: '/accounting/vouchers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminApiKeysRoute = AdminApiKeysRouteImport.update({
  id: '/admin/api-keys',
  path: '/admin/api-keys',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuditLogRoute = AdminAuditLogRouteImport.update({
  id: '/admin/audit-log',
  path: '/admin/audit-log',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBillingRoute = AdminBillingRouteImport.update({
  id: '/admin/billing',
  path: '/admin/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDepartmentsRoute = AdminDepartmentsRouteImport.update({
  id: '/admin/departments',
  path: '/admin/departments',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIntegrationsRoute = AdminIntegrationsRouteImport.update({
  id: '/admin/integrations',
  path: '/admin/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRolesRoute = AdminRolesRouteImport.update({
  id: '/admin/roles',
  path: '/admin/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTeamsRoute = AdminTeamsRouteImport.update({
  id: '/admin/teams',
  path: '/admin/teams',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const BankingAccountsRoute = BankingAccountsRouteImport.update({
  id: '/banking/accounts',
  path: '/banking/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const BankingStatementsRoute = BankingStatementsRouteImport.update({
  id: '/banking/statements',
  path: '/banking/statements',
  getParentRoute: () => rootRouteImport,
} as any)
const BankingTransactionsRoute = BankingTransactionsRouteImport.update({
  id: '/banking/transactions',
  path: '/banking/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmActivitiesRoute = CrmActivitiesRouteImport.update({
  id: '/crm/activities',
  path: '/crm/activities',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmLeadsRoute = CrmLeadsRouteImport.update({
  id: '/crm/leads',
  path: '/crm/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmOpportunitiesRoute = CrmOpportunitiesRouteImport.update({
  id: '/crm/opportunities',
  path: '/crm/opportunities',
  getParentRoute: () => rootRouteImport,
} as any)
const HrmsAttendanceRoute = HrmsAttendanceRouteImport.update({
  id: '/hrms/attendance',
  path: '/hrms/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const HrmsEmployeesRoute = HrmsEmployeesRouteImport.update({
  id: '/hrms/employees',
  path: '/hrms/employees',
  getParentRoute: () => rootRouteImport,
} as any)
const HrmsLeavesRoute = HrmsLeavesRouteImport.update({
  id: '/hrms/leaves',
  path: '/hrms/leaves',
  getParentRoute: () => rootRouteImport,
} as any)
const HrmsPayrollRoute = HrmsPayrollRouteImport.update({
  id: '/hrms/payroll',
  path: '/hrms/payroll',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryCategoriesRoute = InventoryCategoriesRouteImport.update({
  id: '/inventory/categories',
  path: '/inventory/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryLowStockRoute = InventoryLowStockRouteImport.update({
  id: '/inventory/low-stock',
  path: '/inventory/low-stock',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryProductsRoute = InventoryProductsRouteImport.update({
  id: '/inventory/products',
  path: '/inventory/products',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryStockMovementsRoute = InventoryStockMovementsRouteImport.update({
  id: '/inventory/stock-movements',
  path: '/inventory/stock-movements',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryWarehousesRoute = InventoryWarehousesRouteImport.update({
  id: '/inventory/warehouses',
  path: '/inventory/warehouses',
  getParentRoute: () => rootRouteImport,
} as any)
const OperationsComplianceRoute = OperationsComplianceRouteImport.update({
  id: '/operations/compliance',
  path: '/operations/compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const OperationsWorkflowsRoute = OperationsWorkflowsRouteImport.update({
  id: '/operations/workflows',
  path: '/operations/workflows',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchasesBillsRoute = PurchasesBillsRouteImport.update({
  id: '/purchases/bills',
  path: '/purchases/bills',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchasesExpensesRoute = PurchasesExpensesRouteImport.update({
  id: '/purchases/expenses',
  path: '/purchases/expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchasesPurchaseOrdersRoute = PurchasesPurchaseOrdersRouteImport.update({
  id: '/purchases/purchase-orders',
  path: '/purchases/purchase-orders',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchasesVendorsRoute = PurchasesVendorsRouteImport.update({
  id: '/purchases/vendors',
  path: '/purchases/vendors',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsFinancialRoute = ReportsFinancialRouteImport.update({
  id: '/reports/financial',
  path: '/reports/financial',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsGstRoute = ReportsGstRouteImport.update({
  id: '/reports/gst',
  path: '/reports/gst',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsInventoryRoute = ReportsInventoryRouteImport.update({
  id: '/reports/inventory',
  path: '/reports/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsSalesRoute = ReportsSalesRouteImport.update({
  id: '/reports/sales',
  path: '/reports/sales',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesCustomersRoute = SalesCustomersRouteImport.update({
  id: '/sales/customers',
  path: '/sales/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesInvoicesRoute = SalesInvoicesRouteImport.update({
  id: '/sales/invoices',
  path: '/sales/invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesPaymentsRoute = SalesPaymentsRouteImport.update({
  id: '/sales/payments',
  path: '/sales/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesQuotationsRoute = SalesQuotationsRouteImport.update({
  id: '/sales/quotations',
  path: '/sales/quotations',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesSalesOrdersRoute = SalesSalesOrdersRouteImport.update({
  id: '/sales/sales-orders',
  path: '/sales/sales-orders',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityMfaRoute = SecurityMfaRouteImport.update({
  id: '/security/mfa',
  path: '/security/mfa',
  getParentRoute: () => rootRouteImport,
} as any)
const SecuritySessionsRoute = SecuritySessionsRouteImport.update({
  id: '/security/sessions',
  path: '/security/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminAnnouncementsRoute = SuperAdminAnnouncementsRouteImport.update({
  id: '/super-admin/announcements',
  path: '/super-admin/announcements',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminApiUsageRoute = SuperAdminApiUsageRouteImport.update({
  id: '/super-admin/api-usage',
  path: '/super-admin/api-usage',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminAuditLogsRoute = SuperAdminAuditLogsRouteImport.update({
  id: '/super-admin/audit-logs',
  path: '/super-admin/audit-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminCouponsRoute = SuperAdminCouponsRouteImport.update({
  id: '/super-admin/coupons',
  path: '/super-admin/coupons',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminDashboardRoute = SuperAdminDashboardRouteImport.update({
  id: '/super-admin/dashboard',
  path: '/super-admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminFeaturesRoute = SuperAdminFeaturesRouteImport.update({
  id: '/super-admin/features',
  path: '/super-admin/features',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminInvoicesRoute = SuperAdminInvoicesRouteImport.update({
  id: '/super-admin/invoices',
  path: '/super-admin/invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminOrganizationsRoute = SuperAdminOrganizationsRouteImport.update({
  id: '/super-admin/organizations',
  path: '/super-admin/organizations',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminPaymentsRoute = SuperAdminPaymentsRouteImport.update({
  id: '/super-admin/payments',
  path: '/super-admin/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminPermissionsRoute = SuperAdminPermissionsRouteImport.update({
  id: '/super-admin/permissions',
  path: '/super-admin/permissions',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminRolesRoute = SuperAdminRolesRouteImport.update({
  id: '/super-admin/roles',
  path: '/super-admin/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminSettingsRoute = SuperAdminSettingsRouteImport.update({
  id: '/super-admin/settings',
  path: '/super-admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminSubscriptionsRoute = SuperAdminSubscriptionsRouteImport.update({
  id: '/super-admin/subscriptions',
  path: '/super-admin/subscriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminSystemHealthRoute = SuperAdminSystemHealthRouteImport.update({
  id: '/super-admin/system-health',
  path: '/super-admin/system-health',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminUsersRoute = SuperAdminUsersRouteImport.update({
  id: '/super-admin/users',
  path: '/super-admin/users',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/notifications': typeof NotificationsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/accounting/account-groups': typeof AccountingAccountGroupsRoute
  '/accounting/balance-sheet': typeof AccountingBalanceSheetRoute
  '/accounting/books': typeof AccountingBooksRoute
  '/accounting/cash-flow': typeof AccountingCashFlowRoute
  '/accounting/chart-of-accounts': typeof AccountingChartOfAccountsRoute
  '/accounting/cost-centres': typeof AccountingCostCentresRoute
  '/accounting/fiscal-years': typeof AccountingFiscalYearsRoute
  '/accounting/journal-entries': typeof AccountingJournalEntriesRoute
  '/accounting/ledgers': typeof AccountingLedgersRoute
  '/accounting/profit-loss': typeof AccountingProfitLossRoute
  '/accounting/receivables': typeof AccountingReceivablesRoute
  '/accounting/trial-balance': typeof AccountingTrialBalanceRoute
  '/accounting/vouchers': typeof AccountingVouchersRoute
  '/admin/api-keys': typeof AdminApiKeysRoute
  '/admin/audit-log': typeof AdminAuditLogRoute
  '/admin/billing': typeof AdminBillingRoute
  '/admin/departments': typeof AdminDepartmentsRoute
  '/admin/integrations': typeof AdminIntegrationsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/teams': typeof AdminTeamsRoute
  '/admin/users': typeof AdminUsersRoute
  '/banking/accounts': typeof BankingAccountsRoute
  '/banking/statements': typeof BankingStatementsRoute
  '/banking/transactions': typeof BankingTransactionsRoute
  '/crm/activities': typeof CrmActivitiesRoute
  '/crm/leads': typeof CrmLeadsRoute
  '/crm/opportunities': typeof CrmOpportunitiesRoute
  '/hrms/attendance': typeof HrmsAttendanceRoute
  '/hrms/employees': typeof HrmsEmployeesRoute
  '/hrms/leaves': typeof HrmsLeavesRoute
  '/hrms/payroll': typeof HrmsPayrollRoute
  '/inventory/categories': typeof InventoryCategoriesRoute
  '/inventory/low-stock': typeof InventoryLowStockRoute
  '/inventory/products': typeof InventoryProductsRoute
  '/inventory/stock-movements': typeof InventoryStockMovementsRoute
  '/inventory/warehouses': typeof InventoryWarehousesRoute
  '/operations/compliance': typeof OperationsComplianceRoute
  '/operations/workflows': typeof OperationsWorkflowsRoute
  '/purchases/bills': typeof PurchasesBillsRoute
  '/purchases/expenses': typeof PurchasesExpensesRoute
  '/purchases/purchase-orders': typeof PurchasesPurchaseOrdersRoute
  '/purchases/vendors': typeof PurchasesVendorsRoute
  '/reports/financial': typeof ReportsFinancialRoute
  '/reports/gst': typeof ReportsGstRoute
  '/reports/inventory': typeof ReportsInventoryRoute
  '/reports/sales': typeof ReportsSalesRoute
  '/sales/customers': typeof SalesCustomersRoute
  '/sales/invoices': typeof SalesInvoicesRoute
  '/sales/payments': typeof SalesPaymentsRoute
  '/sales/quotations': typeof SalesQuotationsRoute
  '/sales/sales-orders': typeof SalesSalesOrdersRoute
  '/security/mfa': typeof SecurityMfaRoute
  '/security/sessions': typeof SecuritySessionsRoute
  '/super-admin/announcements': typeof SuperAdminAnnouncementsRoute
  '/super-admin/api-usage': typeof SuperAdminApiUsageRoute
  '/super-admin/audit-logs': typeof SuperAdminAuditLogsRoute
  '/super-admin/coupons': typeof SuperAdminCouponsRoute
  '/super-admin/dashboard': typeof SuperAdminDashboardRoute
  '/super-admin/features': typeof SuperAdminFeaturesRoute
  '/super-admin/invoices': typeof SuperAdminInvoicesRoute
  '/super-admin/organizations': typeof SuperAdminOrganizationsRoute
  '/super-admin/payments': typeof SuperAdminPaymentsRoute
  '/super-admin/permissions': typeof SuperAdminPermissionsRoute
  '/super-admin/roles': typeof SuperAdminRolesRoute
  '/super-admin/settings': typeof SuperAdminSettingsRoute
  '/super-admin/subscriptions': typeof SuperAdminSubscriptionsRoute
  '/super-admin/system-health': typeof SuperAdminSystemHealthRoute
  '/super-admin/users': typeof SuperAdminUsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/notifications': typeof NotificationsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/accounting/account-groups': typeof AccountingAccountGroupsRoute
  '/accounting/balance-sheet': typeof AccountingBalanceSheetRoute
  '/accounting/books': typeof AccountingBooksRoute
  '/accounting/cash-flow': typeof AccountingCashFlowRoute
  '/accounting/chart-of-accounts': typeof AccountingChartOfAccountsRoute
  '/accounting/cost-centres': typeof AccountingCostCentresRoute
  '/accounting/fiscal-years': typeof AccountingFiscalYearsRoute
  '/accounting/journal-entries': typeof AccountingJournalEntriesRoute
  '/accounting/ledgers': typeof AccountingLedgersRoute
  '/accounting/profit-loss': typeof AccountingProfitLossRoute
  '/accounting/receivables': typeof AccountingReceivablesRoute
  '/accounting/trial-balance': typeof AccountingTrialBalanceRoute
  '/accounting/vouchers': typeof AccountingVouchersRoute
  '/admin/api-keys': typeof AdminApiKeysRoute
  '/admin/audit-log': typeof AdminAuditLogRoute
  '/admin/billing': typeof AdminBillingRoute
  '/admin/departments': typeof AdminDepartmentsRoute
  '/admin/integrations': typeof AdminIntegrationsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/teams': typeof AdminTeamsRoute
  '/admin/users': typeof AdminUsersRoute
  '/banking/accounts': typeof BankingAccountsRoute
  '/banking/statements': typeof BankingStatementsRoute
  '/banking/transactions': typeof BankingTransactionsRoute
  '/crm/activities': typeof CrmActivitiesRoute
  '/crm/leads': typeof CrmLeadsRoute
  '/crm/opportunities': typeof CrmOpportunitiesRoute
  '/hrms/attendance': typeof HrmsAttendanceRoute
  '/hrms/employees': typeof HrmsEmployeesRoute
  '/hrms/leaves': typeof HrmsLeavesRoute
  '/hrms/payroll': typeof HrmsPayrollRoute
  '/inventory/categories': typeof InventoryCategoriesRoute
  '/inventory/low-stock': typeof InventoryLowStockRoute
  '/inventory/products': typeof InventoryProductsRoute
  '/inventory/stock-movements': typeof InventoryStockMovementsRoute
  '/inventory/warehouses': typeof InventoryWarehousesRoute
  '/operations/compliance': typeof OperationsComplianceRoute
  '/operations/workflows': typeof OperationsWorkflowsRoute
  '/purchases/bills': typeof PurchasesBillsRoute
  '/purchases/expenses': typeof PurchasesExpensesRoute
  '/purchases/purchase-orders': typeof PurchasesPurchaseOrdersRoute
  '/purchases/vendors': typeof PurchasesVendorsRoute
  '/reports/financial': typeof ReportsFinancialRoute
  '/reports/gst': typeof ReportsGstRoute
  '/reports/inventory': typeof ReportsInventoryRoute
  '/reports/sales': typeof ReportsSalesRoute
  '/sales/customers': typeof SalesCustomersRoute
  '/sales/invoices': typeof SalesInvoicesRoute
  '/sales/payments': typeof SalesPaymentsRoute
  '/sales/quotations': typeof SalesQuotationsRoute
  '/sales/sales-orders': typeof SalesSalesOrdersRoute
  '/security/mfa': typeof SecurityMfaRoute
  '/security/sessions': typeof SecuritySessionsRoute
  '/super-admin/announcements': typeof SuperAdminAnnouncementsRoute
  '/super-admin/api-usage': typeof SuperAdminApiUsageRoute
  '/super-admin/audit-logs': typeof SuperAdminAuditLogsRoute
  '/super-admin/coupons': typeof SuperAdminCouponsRoute
  '/super-admin/dashboard': typeof SuperAdminDashboardRoute
  '/super-admin/features': typeof SuperAdminFeaturesRoute
  '/super-admin/invoices': typeof SuperAdminInvoicesRoute
  '/super-admin/organizations': typeof SuperAdminOrganizationsRoute
  '/super-admin/payments': typeof SuperAdminPaymentsRoute
  '/super-admin/permissions': typeof SuperAdminPermissionsRoute
  '/super-admin/roles': typeof SuperAdminRolesRoute
  '/super-admin/settings': typeof SuperAdminSettingsRoute
  '/super-admin/subscriptions': typeof SuperAdminSubscriptionsRoute
  '/super-admin/system-health': typeof SuperAdminSystemHealthRoute
  '/super-admin/users': typeof SuperAdminUsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/notifications': typeof NotificationsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/accounting/account-groups': typeof AccountingAccountGroupsRoute
  '/accounting/balance-sheet': typeof AccountingBalanceSheetRoute
  '/accounting/books': typeof AccountingBooksRoute
  '/accounting/cash-flow': typeof AccountingCashFlowRoute
  '/accounting/chart-of-accounts': typeof AccountingChartOfAccountsRoute
  '/accounting/cost-centres': typeof AccountingCostCentresRoute
  '/accounting/fiscal-years': typeof AccountingFiscalYearsRoute
  '/accounting/journal-entries': typeof AccountingJournalEntriesRoute
  '/accounting/ledgers': typeof AccountingLedgersRoute
  '/accounting/profit-loss': typeof AccountingProfitLossRoute
  '/accounting/receivables': typeof AccountingReceivablesRoute
  '/accounting/trial-balance': typeof AccountingTrialBalanceRoute
  '/accounting/vouchers': typeof AccountingVouchersRoute
  '/admin/api-keys': typeof AdminApiKeysRoute
  '/admin/audit-log': typeof AdminAuditLogRoute
  '/admin/billing': typeof AdminBillingRoute
  '/admin/departments': typeof AdminDepartmentsRoute
  '/admin/integrations': typeof AdminIntegrationsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/teams': typeof AdminTeamsRoute
  '/admin/users': typeof AdminUsersRoute
  '/banking/accounts': typeof BankingAccountsRoute
  '/banking/statements': typeof BankingStatementsRoute
  '/banking/transactions': typeof BankingTransactionsRoute
  '/crm/activities': typeof CrmActivitiesRoute
  '/crm/leads': typeof CrmLeadsRoute
  '/crm/opportunities': typeof CrmOpportunitiesRoute
  '/hrms/attendance': typeof HrmsAttendanceRoute
  '/hrms/employees': typeof HrmsEmployeesRoute
  '/hrms/leaves': typeof HrmsLeavesRoute
  '/hrms/payroll': typeof HrmsPayrollRoute
  '/inventory/categories': typeof InventoryCategoriesRoute
  '/inventory/low-stock': typeof InventoryLowStockRoute
  '/inventory/products': typeof InventoryProductsRoute
  '/inventory/stock-movements': typeof InventoryStockMovementsRoute
  '/inventory/warehouses': typeof InventoryWarehousesRoute
  '/operations/compliance': typeof OperationsComplianceRoute
  '/operations/workflows': typeof OperationsWorkflowsRoute
  '/purchases/bills': typeof PurchasesBillsRoute
  '/purchases/expenses': typeof PurchasesExpensesRoute
  '/purchases/purchase-orders': typeof PurchasesPurchaseOrdersRoute
  '/purchases/vendors': typeof PurchasesVendorsRoute
  '/reports/financial': typeof ReportsFinancialRoute
  '/reports/gst': typeof ReportsGstRoute
  '/reports/inventory': typeof ReportsInventoryRoute
  '/reports/sales': typeof ReportsSalesRoute
  '/sales/customers': typeof SalesCustomersRoute
  '/sales/invoices': typeof SalesInvoicesRoute
  '/sales/payments': typeof SalesPaymentsRoute
  '/sales/quotations': typeof SalesQuotationsRoute
  '/sales/sales-orders': typeof SalesSalesOrdersRoute
  '/security/mfa': typeof SecurityMfaRoute
  '/security/sessions': typeof SecuritySessionsRoute
  '/super-admin/announcements': typeof SuperAdminAnnouncementsRoute
  '/super-admin/api-usage': typeof SuperAdminApiUsageRoute
  '/super-admin/audit-logs': typeof SuperAdminAuditLogsRoute
  '/super-admin/coupons': typeof SuperAdminCouponsRoute
  '/super-admin/dashboard': typeof SuperAdminDashboardRoute
  '/super-admin/features': typeof SuperAdminFeaturesRoute
  '/super-admin/invoices': typeof SuperAdminInvoicesRoute
  '/super-admin/organizations': typeof SuperAdminOrganizationsRoute
  '/super-admin/payments': typeof SuperAdminPaymentsRoute
  '/super-admin/permissions': typeof SuperAdminPermissionsRoute
  '/super-admin/roles': typeof SuperAdminRolesRoute
  '/super-admin/settings': typeof SuperAdminSettingsRoute
  '/super-admin/subscriptions': typeof SuperAdminSubscriptionsRoute
  '/super-admin/system-health': typeof SuperAdminSystemHealthRoute
  '/super-admin/users': typeof SuperAdminUsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accept-invite'
    | '/auth'
    | '/forgot-password'
    | '/notifications'
    | '/reset-password'
    | '/verify-email'
    | '/accounting/account-groups'
    | '/accounting/balance-sheet'
    | '/accounting/books'
    | '/accounting/cash-flow'
    | '/accounting/chart-of-accounts'
    | '/accounting/cost-centres'
    | '/accounting/fiscal-years'
    | '/accounting/journal-entries'
    | '/accounting/ledgers'
    | '/accounting/profit-loss'
    | '/accounting/receivables'
    | '/accounting/trial-balance'
    | '/accounting/vouchers'
    | '/admin/api-keys'
    | '/admin/audit-log'
    | '/admin/billing'
    | '/admin/departments'
    | '/admin/integrations'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/teams'
    | '/admin/users'
    | '/banking/accounts'
    | '/banking/statements'
    | '/banking/transactions'
    | '/crm/activities'
    | '/crm/leads'
    | '/crm/opportunities'
    | '/hrms/attendance'
    | '/hrms/employees'
    | '/hrms/leaves'
    | '/hrms/payroll'
    | '/inventory/categories'
    | '/inventory/low-stock'
    | '/inventory/products'
    | '/inventory/stock-movements'
    | '/inventory/warehouses'
    | '/operations/compliance'
    | '/operations/workflows'
    | '/purchases/bills'
    | '/purchases/expenses'
    | '/purchases/purchase-orders'
    | '/purchases/vendors'
    | '/reports/financial'
    | '/reports/gst'
    | '/reports/inventory'
    | '/reports/sales'
    | '/sales/customers'
    | '/sales/invoices'
    | '/sales/payments'
    | '/sales/quotations'
    | '/sales/sales-orders'
    | '/security/mfa'
    | '/security/sessions'
    | '/super-admin/announcements'
    | '/super-admin/api-usage'
    | '/super-admin/audit-logs'
    | '/super-admin/coupons'
    | '/super-admin/dashboard'
    | '/super-admin/features'
    | '/super-admin/invoices'
    | '/super-admin/organizations'
    | '/super-admin/payments'
    | '/super-admin/permissions'
    | '/super-admin/roles'
    | '/super-admin/settings'
    | '/super-admin/subscriptions'
    | '/super-admin/system-health'
    | '/super-admin/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accept-invite'
    | '/auth'
    | '/forgot-password'
    | '/notifications'
    | '/reset-password'
    | '/verify-email'
    | '/accounting/account-groups'
    | '/accounting/balance-sheet'
    | '/accounting/books'
    | '/accounting/cash-flow'
    | '/accounting/chart-of-accounts'
    | '/accounting/cost-centres'
    | '/accounting/fiscal-years'
    | '/accounting/journal-entries'
    | '/accounting/ledgers'
    | '/accounting/profit-loss'
    | '/accounting/receivables'
    | '/accounting/trial-balance'
    | '/accounting/vouchers'
    | '/admin/api-keys'
    | '/admin/audit-log'
    | '/admin/billing'
    | '/admin/departments'
    | '/admin/integrations'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/teams'
    | '/admin/users'
    | '/banking/accounts'
    | '/banking/statements'
    | '/banking/transactions'
    | '/crm/activities'
    | '/crm/leads'
    | '/crm/opportunities'
    | '/hrms/attendance'
    | '/hrms/employees'
    | '/hrms/leaves'
    | '/hrms/payroll'
    | '/inventory/categories'
    | '/inventory/low-stock'
    | '/inventory/products'
    | '/inventory/stock-movements'
    | '/inventory/warehouses'
    | '/operations/compliance'
    | '/operations/workflows'
    | '/purchases/bills'
    | '/purchases/expenses'
    | '/purchases/purchase-orders'
    | '/purchases/vendors'
    | '/reports/financial'
    | '/reports/gst'
    | '/reports/inventory'
    | '/reports/sales'
    | '/sales/customers'
    | '/sales/invoices'
    | '/sales/payments'
    | '/sales/quotations'
    | '/sales/sales-orders'
    | '/security/mfa'
    | '/security/sessions'
    | '/super-admin/announcements'
    | '/super-admin/api-usage'
    | '/super-admin/audit-logs'
    | '/super-admin/coupons'
    | '/super-admin/dashboard'
    | '/super-admin/features'
    | '/super-admin/invoices'
    | '/super-admin/organizations'
    | '/super-admin/payments'
    | '/super-admin/permissions'
    | '/super-admin/roles'
    | '/super-admin/settings'
    | '/super-admin/subscriptions'
    | '/super-admin/system-health'
    | '/super-admin/users'
  id:
    | '__root__'
    | '/'
    | '/accept-invite'
    | '/auth'
    | '/forgot-password'
    | '/notifications'
    | '/reset-password'
    | '/verify-email'
    | '/accounting/account-groups'
    | '/accounting/balance-sheet'
    | '/accounting/books'
    | '/accounting/cash-flow'
    | '/accounting/chart-of-accounts'
    | '/accounting/cost-centres'
    | '/accounting/fiscal-years'
    | '/accounting/journal-entries'
    | '/accounting/ledgers'
    | '/accounting/profit-loss'
    | '/accounting/receivables'
    | '/accounting/trial-balance'
    | '/accounting/vouchers'
    | '/admin/api-keys'
    | '/admin/audit-log'
    | '/admin/billing'
    | '/admin/departments'
    | '/admin/integrations'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/teams'
    | '/admin/users'
    | '/banking/accounts'
    | '/banking/statements'
    | '/banking/transactions'
    | '/crm/activities'
    | '/crm/leads'
    | '/crm/opportunities'
    | '/hrms/attendance'
    | '/hrms/employees'
    | '/hrms/leaves'
    | '/hrms/payroll'
    | '/inventory/categories'
    | '/inventory/low-stock'
    | '/inventory/products'
    | '/inventory/stock-movements'
    | '/inventory/warehouses'
    | '/operations/compliance'
    | '/operations/workflows'
    | '/purchases/bills'
    | '/purchases/expenses'
    | '/purchases/purchase-orders'
    | '/purchases/vendors'
    | '/reports/financial'
    | '/reports/gst'
    | '/reports/inventory'
    | '/reports/sales'
    | '/sales/customers'
    | '/sales/invoices'
    | '/sales/payments'
    | '/sales/quotations'
    | '/sales/sales-orders'
    | '/security/mfa'
    | '/security/sessions'
    | '/super-admin/announcements'
    | '/super-admin/api-usage'
    | '/super-admin/audit-logs'
    | '/super-admin/coupons'
    | '/super-admin/dashboard'
    | '/super-admin/features'
    | '/super-admin/invoices'
    | '/super-admin/organizations'
    | '/super-admin/payments'
    | '/super-admin/permissions'
    | '/super-admin/roles'
    | '/super-admin/settings'
    | '/super-admin/subscriptions'
    | '/super-admin/system-health'
    | '/super-admin/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcceptInviteRoute: typeof AcceptInviteRoute
  AuthRoute: typeof AuthRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  NotificationsRoute: typeof NotificationsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  AccountingAccountGroupsRoute: typeof AccountingAccountGroupsRoute
  AccountingBalanceSheetRoute: typeof AccountingBalanceSheetRoute
  AccountingBooksRoute: typeof AccountingBooksRoute
  AccountingCashFlowRoute: typeof AccountingCashFlowRoute
  AccountingChartOfAccountsRoute: typeof AccountingChartOfAccountsRoute
  AccountingCostCentresRoute: typeof AccountingCostCentresRoute
  AccountingFiscalYearsRoute: typeof AccountingFiscalYearsRoute
  AccountingJournalEntriesRoute: typeof AccountingJournalEntriesRoute
  AccountingLedgersRoute: typeof AccountingLedgersRoute
  AccountingProfitLossRoute: typeof AccountingProfitLossRoute
  AccountingReceivablesRoute: typeof AccountingReceivablesRoute
  AccountingTrialBalanceRoute: typeof AccountingTrialBalanceRoute
  AccountingVouchersRoute: typeof AccountingVouchersRoute
  AdminApiKeysRoute: typeof AdminApiKeysRoute
  AdminAuditLogRoute: typeof AdminAuditLogRoute
  AdminBillingRoute: typeof AdminBillingRoute
  AdminDepartmentsRoute: typeof AdminDepartmentsRoute
  AdminIntegrationsRoute: typeof AdminIntegrationsRoute
  AdminRolesRoute: typeof AdminRolesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminTeamsRoute: typeof AdminTeamsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  BankingAccountsRoute: typeof BankingAccountsRoute
  BankingStatementsRoute: typeof BankingStatementsRoute
  BankingTransactionsRoute: typeof BankingTransactionsRoute
  CrmActivitiesRoute: typeof CrmActivitiesRoute
  CrmLeadsRoute: typeof CrmLeadsRoute
  CrmOpportunitiesRoute: typeof CrmOpportunitiesRoute
  HrmsAttendanceRoute: typeof HrmsAttendanceRoute
  HrmsEmployeesRoute: typeof HrmsEmployeesRoute
  HrmsLeavesRoute: typeof HrmsLeavesRoute
  HrmsPayrollRoute: typeof HrmsPayrollRoute
  InventoryCategoriesRoute: typeof InventoryCategoriesRoute
  InventoryLowStockRoute: typeof InventoryLowStockRoute
  InventoryProductsRoute: typeof InventoryProductsRoute
  InventoryStockMovementsRoute: typeof InventoryStockMovementsRoute
  InventoryWarehousesRoute: typeof InventoryWarehousesRoute
  OperationsComplianceRoute: typeof OperationsComplianceRoute
  OperationsWorkflowsRoute: typeof OperationsWorkflowsRoute
  PurchasesBillsRoute: typeof PurchasesBillsRoute
  PurchasesExpensesRoute: typeof PurchasesExpensesRoute
  PurchasesPurchaseOrdersRoute: typeof PurchasesPurchaseOrdersRoute
  PurchasesVendorsRoute: typeof PurchasesVendorsRoute
  ReportsFinancialRoute: typeof ReportsFinancialRoute
  ReportsGstRoute: typeof ReportsGstRoute
  ReportsInventoryRoute: typeof ReportsInventoryRoute
  ReportsSalesRoute: typeof ReportsSalesRoute
  SalesCustomersRoute: typeof SalesCustomersRoute
  SalesInvoicesRoute: typeof SalesInvoicesRoute
  SalesPaymentsRoute: typeof SalesPaymentsRoute
  SalesQuotationsRoute: typeof SalesQuotationsRoute
  SalesSalesOrdersRoute: typeof SalesSalesOrdersRoute
  SecurityMfaRoute: typeof SecurityMfaRoute
  SecuritySessionsRoute: typeof SecuritySessionsRoute
  SuperAdminAnnouncementsRoute: typeof SuperAdminAnnouncementsRoute
  SuperAdminApiUsageRoute: typeof SuperAdminApiUsageRoute
  SuperAdminAuditLogsRoute: typeof SuperAdminAuditLogsRoute
  SuperAdminCouponsRoute: typeof SuperAdminCouponsRoute
  SuperAdminDashboardRoute: typeof SuperAdminDashboardRoute
  SuperAdminFeaturesRoute: typeof SuperAdminFeaturesRoute
  SuperAdminInvoicesRoute: typeof SuperAdminInvoicesRoute
  SuperAdminOrganizationsRoute: typeof SuperAdminOrganizationsRoute
  SuperAdminPaymentsRoute: typeof SuperAdminPaymentsRoute
  SuperAdminPermissionsRoute: typeof SuperAdminPermissionsRoute
  SuperAdminRolesRoute: typeof SuperAdminRolesRoute
  SuperAdminSettingsRoute: typeof SuperAdminSettingsRoute
  SuperAdminSubscriptionsRoute: typeof SuperAdminSubscriptionsRoute
  SuperAdminSystemHealthRoute: typeof SuperAdminSystemHealthRoute
  SuperAdminUsersRoute: typeof SuperAdminUsersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invite': {
      id: '/accept-invite'
      path: '/accept-invite'
      fullPath: '/accept-invite'
      preLoaderRoute: typeof AcceptInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounting/account-groups': {
      id: '/accounting/account-groups'
      path: '/accounting/account-groups'
      fullPath: '/accounting/account-groups'
      preLoaderRoute: typeof AccountingAccountGroupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounting/balance-sheet': {
      id: '/accounting/balance-sheet'
      path: '/accounting/balance-sheet'
      fullPath: '/accounting/balance-sheet'
      preLoaderRoute: typeof AccountingBalanceSheetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounting/books': {
      id: '/accounting/books'
      path: '/accounting/books'
      fullPath: '/accounting/books'
      preLoaderRoute: typeof AccountingBooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounting/cash-flow': {
      id: '/accounting/cash-flow'
      path: '/accounting/cash-flow'
      fullPath: '/accounting/cash-flow'
      preLoaderRoute: typeof AccountingCashFlowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounting/chart-of-accounts': {
      id: '/accounting/chart-of-accounts'
      path: '/accounting/chart-of-accounts'
      fullPath: '/accounting/chart-of-accounts'
      preLoaderRoute: typeof AccountingChartOfAccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounting/cost-centres': {
      id: '/accounting/cost-centres'
      path: '/accounting/cost-centres'
      fullPath: '/accounting/cost-centres'
      preLoaderRoute: typeof AccountingCostCentresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounting/fiscal-years': {
      id: '/accounting/fiscal-years'
      path: '/accounting/fiscal-years'
      fullPath: '/accounting/fiscal-years'
      preLoaderRoute: typeof AccountingFiscalYearsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounting/journal-entries': {
      id: '/accounting/journal-entries'
      path: '/accounting/journal-entries'
      fullPath: '/accounting/journal-entries'
      preLoaderRoute: typeof AccountingJournalEntriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounting/ledgers': {
      id: '/accounting/ledgers'
      path: '/accounting/ledgers'
      fullPath: '/accounting/ledgers'
      preLoaderRoute: typeof AccountingLedgersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounting/profit-loss': {
      id: '/accounting/profit-loss'
      path: '/accounting/profit-loss'
      fullPath: '/accounting/profit-loss'
      preLoaderRoute: typeof AccountingProfitLossRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounting/receivables': {
      id: '/accounting/receivables'
      path: '/accounting/receivables'
      fullPath: '/accounting/receivables'
      preLoaderRoute: typeof AccountingReceivablesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounting/trial-balance': {
      id: '/accounting/trial-balance'
      path: '/accounting/trial-balance'
      fullPath: '/accounting/trial-balance'
      preLoaderRoute: typeof AccountingTrialBalanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounting/vouchers': {
      id: '/accounting/vouchers'
      path: '/accounting/vouchers'
      fullPath: '/accounting/vouchers'
      preLoaderRoute: typeof AccountingVouchersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/api-keys': {
      id: '/admin/api-keys'
      path: '/admin/api-keys'
      fullPath: '/admin/api-keys'
      preLoaderRoute: typeof AdminApiKeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/audit-log': {
      id: '/admin/audit-log'
      path: '/admin/audit-log'
      fullPath: '/admin/audit-log'
      preLoaderRoute: typeof AdminAuditLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/billing': {
      id: '/admin/billing'
      path: '/admin/billing'
      fullPath: '/admin/billing'
      preLoaderRoute: typeof AdminBillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/departments': {
      id: '/admin/departments'
      path: '/admin/departments'
      fullPath: '/admin/departments'
      preLoaderRoute: typeof AdminDepartmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/integrations': {
      id: '/admin/integrations'
      path: '/admin/integrations'
      fullPath: '/admin/integrations'
      preLoaderRoute: typeof AdminIntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/roles': {
      id: '/admin/roles'
      path: '/admin/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AdminRolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/teams': {
      id: '/admin/teams'
      path: '/admin/teams'
      fullPath: '/admin/teams'
      preLoaderRoute: typeof AdminTeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/banking/accounts': {
      id: '/banking/accounts'
      path: '/banking/accounts'
      fullPath: '/banking/accounts'
      preLoaderRoute: typeof BankingAccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/banking/statements': {
      id: '/banking/statements'
      path: '/banking/statements'
      fullPath: '/banking/statements'
      preLoaderRoute: typeof BankingStatementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/banking/transactions': {
      id: '/banking/transactions'
      path: '/banking/transactions'
      fullPath: '/banking/transactions'
      preLoaderRoute: typeof BankingTransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm/activities': {
      id: '/crm/activities'
      path: '/crm/activities'
      fullPath: '/crm/activities'
      preLoaderRoute: typeof CrmActivitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm/leads': {
      id: '/crm/leads'
      path: '/crm/leads'
      fullPath: '/crm/leads'
      preLoaderRoute: typeof CrmLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm/opportunities': {
      id: '/crm/opportunities'
      path: '/crm/opportunities'
      fullPath: '/crm/opportunities'
      preLoaderRoute: typeof CrmOpportunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hrms/attendance': {
      id: '/hrms/attendance'
      path: '/hrms/attendance'
      fullPath: '/hrms/attendance'
      preLoaderRoute: typeof HrmsAttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hrms/employees': {
      id: '/hrms/employees'
      path: '/hrms/employees'
      fullPath: '/hrms/employees'
      preLoaderRoute: typeof HrmsEmployeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hrms/leaves': {
      id: '/hrms/leaves'
      path: '/hrms/leaves'
      fullPath: '/hrms/leaves'
      preLoaderRoute: typeof HrmsLeavesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hrms/payroll': {
      id: '/hrms/payroll'
      path: '/hrms/payroll'
      fullPath: '/hrms/payroll'
      preLoaderRoute: typeof HrmsPayrollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/categories': {
      id: '/inventory/categories'
      path: '/inventory/categories'
      fullPath: '/inventory/categories'
      preLoaderRoute: typeof InventoryCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/low-stock': {
      id: '/inventory/low-stock'
      path: '/inventory/low-stock'
      fullPath: '/inventory/low-stock'
      preLoaderRoute: typeof InventoryLowStockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/products': {
      id: '/inventory/products'
      path: '/inventory/products'
      fullPath: '/inventory/products'
      preLoaderRoute: typeof InventoryProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/stock-movements': {
      id: '/inventory/stock-movements'
      path: '/inventory/stock-movements'
      fullPath: '/inventory/stock-movements'
      preLoaderRoute: typeof InventoryStockMovementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/warehouses': {
      id: '/inventory/warehouses'
      path: '/inventory/warehouses'
      fullPath: '/inventory/warehouses'
      preLoaderRoute: typeof InventoryWarehousesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operations/compliance': {
      id: '/operations/compliance'
      path: '/operations/compliance'
      fullPath: '/operations/compliance'
      preLoaderRoute: typeof OperationsComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operations/workflows': {
      id: '/operations/workflows'
      path: '/operations/workflows'
      fullPath: '/operations/workflows'
      preLoaderRoute: typeof OperationsWorkflowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchases/bills': {
      id: '/purchases/bills'
      path: '/purchases/bills'
      fullPath: '/purchases/bills'
      preLoaderRoute: typeof PurchasesBillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchases/expenses': {
      id: '/purchases/expenses'
      path: '/purchases/expenses'
      fullPath: '/purchases/expenses'
      preLoaderRoute: typeof PurchasesExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchases/purchase-orders': {
      id: '/purchases/purchase-orders'
      path: '/purchases/purchase-orders'
      fullPath: '/purchases/purchase-orders'
      preLoaderRoute: typeof PurchasesPurchaseOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchases/vendors': {
      id: '/purchases/vendors'
      path: '/purchases/vendors'
      fullPath: '/purchases/vendors'
      preLoaderRoute: typeof PurchasesVendorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/financial': {
      id: '/reports/financial'
      path: '/reports/financial'
      fullPath: '/reports/financial'
      preLoaderRoute: typeof ReportsFinancialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/gst': {
      id: '/reports/gst'
      path: '/reports/gst'
      fullPath: '/reports/gst'
      preLoaderRoute: typeof ReportsGstRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/inventory': {
      id: '/reports/inventory'
      path: '/reports/inventory'
      fullPath: '/reports/inventory'
      preLoaderRoute: typeof ReportsInventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/sales': {
      id: '/reports/sales'
      path: '/reports/sales'
      fullPath: '/reports/sales'
      preLoaderRoute: typeof ReportsSalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales/customers': {
      id: '/sales/customers'
      path: '/sales/customers'
      fullPath: '/sales/customers'
      preLoaderRoute: typeof SalesCustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales/invoices': {
      id: '/sales/invoices'
      path: '/sales/invoices'
      fullPath: '/sales/invoices'
      preLoaderRoute: typeof SalesInvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales/payments': {
      id: '/sales/payments'
      path: '/sales/payments'
      fullPath: '/sales/payments'
      preLoaderRoute: typeof SalesPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales/quotations': {
      id: '/sales/quotations'
      path: '/sales/quotations'
      fullPath: '/sales/quotations'
      preLoaderRoute: typeof SalesQuotationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales/sales-orders': {
      id: '/sales/sales-orders'
      path: '/sales/sales-orders'
      fullPath: '/sales/sales-orders'
      preLoaderRoute: typeof SalesSalesOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security/mfa': {
      id: '/security/mfa'
      path: '/security/mfa'
      fullPath: '/security/mfa'
      preLoaderRoute: typeof SecurityMfaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security/sessions': {
      id: '/security/sessions'
      path: '/security/sessions'
      fullPath: '/security/sessions'
      preLoaderRoute: typeof SecuritySessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin/announcements': {
      id: '/super-admin/announcements'
      path: '/super-admin/announcements'
      fullPath: '/super-admin/announcements'
      preLoaderRoute: typeof SuperAdminAnnouncementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin/api-usage': {
      id: '/super-admin/api-usage'
      path: '/super-admin/api-usage'
      fullPath: '/super-admin/api-usage'
      preLoaderRoute: typeof SuperAdminApiUsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin/audit-logs': {
      id: '/super-admin/audit-logs'
      path: '/super-admin/audit-logs'
      fullPath: '/super-admin/audit-logs'
      preLoaderRoute: typeof SuperAdminAuditLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin/coupons': {
      id: '/super-admin/coupons'
      path: '/super-admin/coupons'
      fullPath: '/super-admin/coupons'
      preLoaderRoute: typeof SuperAdminCouponsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin/dashboard': {
      id: '/super-admin/dashboard'
      path: '/super-admin/dashboard'
      fullPath: '/super-admin/dashboard'
      preLoaderRoute: typeof SuperAdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin/features': {
      id: '/super-admin/features'
      path: '/super-admin/features'
      fullPath: '/super-admin/features'
      preLoaderRoute: typeof SuperAdminFeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin/invoices': {
      id: '/super-admin/invoices'
      path: '/super-admin/invoices'
      fullPath: '/super-admin/invoices'
      preLoaderRoute: typeof SuperAdminInvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin/organizations': {
      id: '/super-admin/organizations'
      path: '/super-admin/organizations'
      fullPath: '/super-admin/organizations'
      preLoaderRoute: typeof SuperAdminOrganizationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin/payments': {
      id: '/super-admin/payments'
      path: '/super-admin/payments'
      fullPath: '/super-admin/payments'
      preLoaderRoute: typeof SuperAdminPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin/permissions': {
      id: '/super-admin/permissions'
      path: '/super-admin/permissions'
      fullPath: '/super-admin/permissions'
      preLoaderRoute: typeof SuperAdminPermissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin/roles': {
      id: '/super-admin/roles'
      path: '/super-admin/roles'
      fullPath: '/super-admin/roles'
      preLoaderRoute: typeof SuperAdminRolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin/settings': {
      id: '/super-admin/settings'
      path: '/super-admin/settings'
      fullPath: '/super-admin/settings'
      preLoaderRoute: typeof SuperAdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin/subscriptions': {
      id: '/super-admin/subscriptions'
      path: '/super-admin/subscriptions'
      fullPath: '/super-admin/subscriptions'
      preLoaderRoute: typeof SuperAdminSubscriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin/system-health': {
      id: '/super-admin/system-health'
      path: '/super-admin/system-health'
      fullPath: '/super-admin/system-health'
      preLoaderRoute: typeof SuperAdminSystemHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin/users': {
      id: '/super-admin/users'
      path: '/super-admin/users'
      fullPath: '/super-admin/users'
      preLoaderRoute: typeof SuperAdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcceptInviteRoute: AcceptInviteRoute,
  AuthRoute: AuthRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  NotificationsRoute: NotificationsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  AccountingAccountGroupsRoute: AccountingAccountGroupsRoute,
  AccountingBalanceSheetRoute: AccountingBalanceSheetRoute,
  AccountingBooksRoute: AccountingBooksRoute,
  AccountingCashFlowRoute: AccountingCashFlowRoute,
  AccountingChartOfAccountsRoute: AccountingChartOfAccountsRoute,
  AccountingCostCentresRoute: AccountingCostCentresRoute,
  AccountingFiscalYearsRoute: AccountingFiscalYearsRoute,
  AccountingJournalEntriesRoute: AccountingJournalEntriesRoute,
  AccountingLedgersRoute: AccountingLedgersRoute,
  AccountingProfitLossRoute: AccountingProfitLossRoute,
  AccountingReceivablesRoute: AccountingReceivablesRoute,
  AccountingTrialBalanceRoute: AccountingTrialBalanceRoute,
  AccountingVouchersRoute: AccountingVouchersRoute,
  AdminApiKeysRoute: AdminApiKeysRoute,
  AdminAuditLogRoute: AdminAuditLogRoute,
  AdminBillingRoute: AdminBillingRoute,
  AdminDepartmentsRoute: AdminDepartmentsRoute,
  AdminIntegrationsRoute: AdminIntegrationsRoute,
  AdminRolesRoute: AdminRolesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminTeamsRoute: AdminTeamsRoute,
  AdminUsersRoute: AdminUsersRoute,
  BankingAccountsRoute: BankingAccountsRoute,
  BankingStatementsRoute: BankingStatementsRoute,
  BankingTransactionsRoute: BankingTransactionsRoute,
  CrmActivitiesRoute: CrmActivitiesRoute,
  CrmLeadsRoute: CrmLeadsRoute,
  CrmOpportunitiesRoute: CrmOpportunitiesRoute,
  HrmsAttendanceRoute: HrmsAttendanceRoute,
  HrmsEmployeesRoute: HrmsEmployeesRoute,
  HrmsLeavesRoute: HrmsLeavesRoute,
  HrmsPayrollRoute: HrmsPayrollRoute,
  InventoryCategoriesRoute: InventoryCategoriesRoute,
  InventoryLowStockRoute: InventoryLowStockRoute,
  InventoryProductsRoute: InventoryProductsRoute,
  InventoryStockMovementsRoute: InventoryStockMovementsRoute,
  InventoryWarehousesRoute: InventoryWarehousesRoute,
  OperationsComplianceRoute: OperationsComplianceRoute,
  OperationsWorkflowsRoute: OperationsWorkflowsRoute,
  PurchasesBillsRoute: PurchasesBillsRoute,
  PurchasesExpensesRoute: PurchasesExpensesRoute,
  PurchasesPurchaseOrdersRoute: PurchasesPurchaseOrdersRoute,
  PurchasesVendorsRoute: PurchasesVendorsRoute,
  ReportsFinancialRoute: ReportsFinancialRoute,
  ReportsGstRoute: ReportsGstRoute,
  ReportsInventoryRoute: ReportsInventoryRoute,
  ReportsSalesRoute: ReportsSalesRoute,
  SalesCustomersRoute: SalesCustomersRoute,
  SalesInvoicesRoute: SalesInvoicesRoute,
  SalesPaymentsRoute: SalesPaymentsRoute,
  SalesQuotationsRoute: SalesQuotationsRoute,
  SalesSalesOrdersRoute: SalesSalesOrdersRoute,
  SecurityMfaRoute: SecurityMfaRoute,
  SecuritySessionsRoute: SecuritySessionsRoute,
  SuperAdminAnnouncementsRoute: SuperAdminAnnouncementsRoute,
  SuperAdminApiUsageRoute: SuperAdminApiUsageRoute,
  SuperAdminAuditLogsRoute: SuperAdminAuditLogsRoute,
  SuperAdminCouponsRoute: SuperAdminCouponsRoute,
  SuperAdminDashboardRoute: SuperAdminDashboardRoute,
  SuperAdminFeaturesRoute: SuperAdminFeaturesRoute,
  SuperAdminInvoicesRoute: SuperAdminInvoicesRoute,
  SuperAdminOrganizationsRoute: SuperAdminOrganizationsRoute,
  SuperAdminPaymentsRoute: SuperAdminPaymentsRoute,
  SuperAdminPermissionsRoute: SuperAdminPermissionsRoute,
  SuperAdminRolesRoute: SuperAdminRolesRoute,
  SuperAdminSettingsRoute: SuperAdminSettingsRoute,
  SuperAdminSubscriptionsRoute: SuperAdminSubscriptionsRoute,
  SuperAdminSystemHealthRoute: SuperAdminSystemHealthRoute,
  SuperAdminUsersRoute: SuperAdminUsersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
